apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
- name: mysql-pass
  literals:
  - password=*******
resources:
  - efs-provisioner.yaml
  - rbac.yaml
  - storage-class.yaml
  - mysql-deployment.yaml
  - joomla-deployment.yaml